let gameBoard = document.getElementById("game-board");
let replayButton = document.getElementById("replay-button");
let player1Turn = document.getElementById("player1-turn");
let player2Turn = document.getElementById("player2-turn");
let player1Panel = document.getElementById("player1-panel");
let player2Panel = document.getElementById("player2-panel");
let winMessage = document.getElementById("winmessage");
let buttonSimulateHorizontal = document.getElementById("button-simulatehorizontal");
let buttonSimulateVertical = document.getElementById("button-simulatevertical");
let buttonSimulateDiagonal = document.getElementById("button-simulatediagonal");
let buttonSimulateFullBoard = document.getElementById("button-simulatefullboard");
let buttonReset = document.getElementById("button-reset");
let rows, cols, currentPlayer, boardState, gameWon;
let timing = 0;
let timingIncrement = 150;
let simulationInProgress = false;
let direction = 0;
let animationInProgress = false;